name: e2e-cucumber
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress Run
        uses: cypress-io/github-action@v6
      - name: Generate report
        run: npm run cy:report
      - name: Deploy reports page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public